// Loads .env into process.env (shell / Docker build args win) BEFORE anything
// below reads it - Astro's own .env handling only reaches import.meta.env, and
// only after this file has already been evaluated. See scripts/load-env.mjs.
import './scripts/load-env.mjs';

import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Canonical site URL — baked into sitemap / canonical / OG tags, and the
// switch that decides whether analytics are emitted at all (see
// src/lib/analytics.ts). Defaults to production; the dev image can advertise
// dev.docs.openlinker.io.
const site = process.env.SITE_URL ?? 'https://docs.openlinker.io';

// NOTE: nothing GA-related is emitted from this file. Google Analytics is
// owned end to end by src/components/Footer.astro (loader, consent cookie and
// banner), so the measurement ID is read in exactly one place and the gtag
// bootstrap does not depend on how Starlight sorts entries in `head`. See the
// header comment in Footer.astro.

// The sidebar is authored by hand (not autogenerated) so the reading order is
// deliberate and stable regardless of what the sync script pulls from the
// product repo. Every `slug` here must map to a file the sync script writes
// into src/content/docs/ — see scripts/sync-docs.mjs (SOURCES).
export default defineConfig({
  site,
  // Docs are English-only and live at the root (/getting-started/, not
  // /en/getting-started/). The marketing site uses /en/ + /pl/ prefixes, so
  // visitors and cross-site links may hit /en/… here — bounce those to the
  // root equivalent instead of 404ing. If Polish docs ever ship, this becomes
  // a real /pl/ + /en/ locale split (see astro:i18n) rather than a redirect.
  redirects: {
    '/en/[...slug]': '/[...slug]',
  },
  integrations: [
    starlight({
      title: 'OpenLinker Docs',
      description:
        'Documentation for OpenLinker — the open-source, self-hosted e-commerce orchestration platform.',
      tagline: 'Self-hosted · Plugin-native · Apache 2.0',
      logo: {
        // Same transparent (box-less) marks the marketing site uses in its nav:
        // color glyph on the dark header, mono-black on light surfaces.
        light: './src/assets/logo-mono-black.svg',
        dark: './src/assets/logo-color.svg',
        replacesTitle: false,
        alt: 'OpenLinker',
      },
      favicon: '/favicon.svg',
      // Dark is the brand default (matches the marketing site). Starlight
      // still ships a light/dark toggle; OS preference is not auto-followed
      // for first paint because we set the default theme to dark below.
      defaultLocale: 'en',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/openlinker-project/openlinker' },
      ],
      components: {
        // Adds an "openlinker.io ↗" link back to the marketing site in the
        // header, before the default social icons. See HeaderLinks.astro.
        SocialIcons: './src/components/HeaderLinks.astro',
        // Appends a followed link back to openlinker.io in the page footer
        // (reciprocal SEO cross-link, issue #4). See Footer.astro.
        Footer: './src/components/Footer.astro',
      },
      editLink: {
        // Docs are single-sourced from the product repo; "edit" points there.
        baseUrl: 'https://github.com/openlinker-project/openlinker/edit/main/docs/',
      },
      customCss: [
        '@fontsource/ibm-plex-sans/400.css',
        '@fontsource/ibm-plex-sans/500.css',
        '@fontsource/ibm-plex-sans/600.css',
        '@fontsource/ibm-plex-sans/700.css',
        '@fontsource/ibm-plex-mono/400.css',
        '@fontsource/ibm-plex-mono/500.css',
        '@fontsource/ibm-plex-mono/600.css',
        './src/styles/theme.css',
      ],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Introduction', slug: 'index' },
            { label: 'Getting started', slug: 'getting-started' },
            { label: 'One-command demo', slug: 'demo-setup' },
            { label: 'Capabilities', slug: 'capabilities' },
          ],
        },
        {
          label: 'User guide',
          items: [
            { label: 'Overview', slug: 'user-guide/overview' },
            { label: 'Connecting a platform', slug: 'user-guide/connecting-a-platform' },
            { label: 'Catalog & inventory', slug: 'user-guide/catalog-and-inventory' },
            { label: 'Invoices', slug: 'user-guide/invoices' },
            { label: 'Listings', slug: 'user-guide/listings' },
            { label: 'Orders', slug: 'user-guide/orders' },
            { label: 'Analytics', slug: 'user-guide/analytics' },
            { label: 'Diagnostics', slug: 'user-guide/diagnostics' },
            { label: 'Settings & admin', slug: 'user-guide/settings-and-admin' },
          ],
        },
        {
          label: 'Build adapters',
          items: [
            { label: 'Plugin author guide', slug: 'plugin-author-guide' },
            { label: 'Public API', slug: 'public-api' },
            { label: 'Connections & adapter resolution', slug: 'connections-and-adapter-resolution' },
          ],
        },
        {
          label: 'Integrations',
          items: [
            { label: 'PrestaShop', slug: 'integrations/prestashop' },
            { label: 'WooCommerce', slug: 'integrations/woocommerce' },
            { label: 'Allegro', slug: 'integrations/allegro' },
            { label: 'ERLI', slug: 'integrations/erli' },
            { label: 'InPost', slug: 'integrations/inpost' },
            { label: 'DPD', slug: 'integrations/dpd' },
            { label: 'KSeF', slug: 'integrations/ksef' },
            { label: 'Subiekt nexo', slug: 'integrations/subiekt' },
          ],
        },
        {
          label: 'Architecture',
          items: [{ label: 'Architecture overview', slug: 'architecture-overview' }],
        },
        {
          label: 'Operate',
          items: [
            { label: 'Webhooks', slug: 'webhooks/overview' },
            { label: 'PrestaShop webhooks', slug: 'webhooks/prestashop' },
            { label: 'Migrations', slug: 'migrations' },
          ],
        },
      ],
    }),
  ],
});
