import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Canonical site URL — baked into sitemap / canonical / OG tags.
// Defaults to production; the dev image can advertise dev.docs.openlinker.io.
const site = process.env.SITE_URL ?? 'https://docs.openlinker.io';

// The sidebar is authored by hand (not autogenerated) so the reading order is
// deliberate and stable regardless of what the sync script pulls from the
// product repo. Every `slug` here must map to a file the sync script writes
// into src/content/docs/ — see scripts/sync-docs.mjs (SOURCES).
export default defineConfig({
  site,
  integrations: [
    starlight({
      title: 'OpenLinker Docs',
      description:
        'Documentation for OpenLinker — the open-source, self-hosted e-commerce orchestration platform.',
      tagline: 'Self-hosted · Plugin-native · Apache 2.0',
      logo: {
        light: './src/assets/logo-mono-black.svg',
        dark: './src/assets/logo-mono-graphite.svg',
        replacesTitle: false,
        alt: 'OpenLinker',
      },
      favicon: '/favicon.svg',
      // Dark is the brand default (matches the marketing site). Starlight
      // still ships a light/dark toggle; OS preference is not auto-followed
      // for first paint because we set the default theme to dark below.
      defaultLocale: 'en',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/openlinker-project/openlinker' },
      ],
      editLink: {
        // Docs are single-sourced from the product repo; "edit" points there.
        baseUrl: 'https://github.com/openlinker-project/openlinker/edit/main/docs/',
      },
      customCss: [
        '@fontsource/ibm-plex-sans/400.css',
        '@fontsource/ibm-plex-sans/500.css',
        '@fontsource/ibm-plex-sans/600.css',
        '@fontsource/ibm-plex-sans/700.css',
        '@fontsource/ibm-plex-mono/400.css',
        '@fontsource/ibm-plex-mono/500.css',
        '@fontsource/ibm-plex-mono/600.css',
        './src/styles/theme.css',
      ],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Introduction', slug: 'index' },
            { label: 'Getting started', slug: 'getting-started' },
            { label: 'One-command demo', slug: 'demo-setup' },
            { label: 'Capabilities', slug: 'capabilities' },
          ],
        },
        {
          label: 'User guide',
          items: [
            { label: 'Overview', slug: 'user-guide/overview' },
            { label: 'Connecting a platform', slug: 'user-guide/connecting-a-platform' },
            { label: 'Catalog & inventory', slug: 'user-guide/catalog-and-inventory' },
            { label: 'Listings', slug: 'user-guide/listings' },
            { label: 'Orders', slug: 'user-guide/orders' },
            { label: 'Diagnostics', slug: 'user-guide/diagnostics' },
            { label: 'Settings & admin', slug: 'user-guide/settings-and-admin' },
          ],
        },
        {
          label: 'Build adapters',
          items: [
            { label: 'Plugin author guide', slug: 'plugin-author-guide' },
            { label: 'Public API', slug: 'public-api' },
            { label: 'Connections & adapter resolution', slug: 'connections-and-adapter-resolution' },
          ],
        },
        {
          label: 'Architecture',
          items: [{ label: 'Architecture overview', slug: 'architecture-overview' }],
        },
        {
          label: 'Operate',
          items: [
            { label: 'Webhooks', slug: 'webhooks/overview' },
            { label: 'PrestaShop webhooks', slug: 'webhooks/prestashop' },
            { label: 'Migrations', slug: 'migrations' },
          ],
        },
      ],
    }),
  ],
});
